config/routes.rb
TypewriterApi::Application.routes.draw do
  resources :settings

  get "pages/hello"

  resources :jobs do
    collection do 
      get 'lineup'
      get 'refresh'
    end
  end

  root :to => 'pages#hello'

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :content, :owner, :status_code, :tweet_id, :location, :profile_image_url, :user_id, :user_name

  before_save :default_values
  
  def default_values
    self.status_code ||= 'Lined Up'
  end

  scope :tweet, :conditions => ['tweet_id IS NOT NULL']

  def self.load_tweets
    if Job.tweet.count > 0 
      @id = Job.tweet.last.tweet_id
      puts Job.tweet.count
      puts @id
    else
      @id = 100000000
      puts Job.tweet.count
    end
    Twitter.search("#"+Setting.last.hashtag, :since_id=>@id).results.each do |r|
      puts "#{r.id}:#{r.from_user}: #{r.text}"
      #puts r.inspect
      Job.create(:tweet_id => r.id, :owner => r.from_user, :content => r.text, :location => r.user.location, :profile_image_url => r.user.profile_image_url, :user_id =>r.user.id, :user_name => r.user.name) 
    end
  end
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  attr_accessible :camera, :camera_link, :admin_password, :hashtag, :maintanance, :status, :twitter_app_id, :twitter_app_oauth, :twitter_app_oauth_token, :twitter_app_token, :twitter_user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private 

  def authenticate
    if Setting.count > 0
      authenticate_or_request_with_http_basic('Administration') do |username, password|
        username == 'admin' && password == Setting.last.admin_password
      end
    end
  end
end

app/controllers/jobs_controller.rb
require 'rinku'

class JobsController < ApplicationController
  before_filter :authenticate, :except => [:refresh]

  def index
    @jobs = Job.order("id DESC").all

    respond_to do |format|
      format.html
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.text { render text: @job.content }
    end
  end


  # GET /jobs/lineup.text
  def lineup
    # hands out latest job (status not printed)
    if @job = Job.where("status_code = ?", "Lined Up").last
      @job.status_code = "Printed"
      @job.owner
      @job.save
      @printjob = @job.content.downcase
      #@printjob.slice! "@lepetiteprinter"
      @printjob.slice! "#printme"
      @printjob.slice! "@lepetiteprinter"
      if @job.owner
        @printjob = "#{@job.owner.downcase} . "+@printjob
      end
      respond_to do |format|
        format.text { render text: @printjob}
      end
    else
      respond_to do |format|
        format.text { render text: "NULL" }
      end
    end
  end


  # GET refresh
  def refresh
    Job.load_tweets
    redirect_to root_path
  end


  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])
    @job.status_code = "Lined Up"
    respond_to do |format|
      if @job.save

        format.html { redirect_to action: "index"}
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def hello
    @jobs = Job.tweet.order("id DESC").limit(9)
    @settings = Setting.last
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  before_filter :authenticate

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @settings }
    end
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
    @setting = Setting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @setting }
    end
  end

  # GET /settings/new
  # GET /settings/new.json
  def new
    @setting = Setting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @setting }
    end
  end

  # GET /settings/1/edit
  def edit
    @setting = Setting.find(params[:id])
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(params[:setting])

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render json: @setting, status: :created, location: @setting }
      else
        format.html { render action: "new" }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /settings/1
  # PUT /settings/1.json
  def update
    @setting = Setting.find(params[:id])

    respond_to do |format|
      if @setting.update_attributes(params[:setting])
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting = Setting.find(params[:id])
    @setting.destroy

    respond_to do |format|
      format.html { redirect_to settings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/jobs/edit.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/jobs/index.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_job_path,
            :class => 'btn btn-primary' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:owner) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:status_code) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= link_to job.id, job_path(job) %></td>
        <td><% if job.tweet_id %>

              <%= image_tag job.profile_image_url, :class =>"img-circle media-object" %> <%= link_to "@#{job.owner}", "http://www.twitter.com/#{job.owner}" %>
        
            <% else %>
              <%= job.owner %>
            <% end %>
        </td>
        <td><%=raw Rinku.auto_link(job.content, mode=:all) %></td>
        <td>
          <% if job.status_code == 'Lined Up' %>
          <span class="label label-warning"><%= job.status_code %></span>
          
          <% else %>
            <span class="label label-success"><%= job.status_code %></span>
          <% end %>
        </td>
        <td><%=l job.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_job_path(job), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      job_path(job),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/hello.html.erb
   <div class="row">
        <div class="span7">
          

     
          <% if @settings.maintanance == false %>
          <table class="table table-striped">
            <tbody>
              <% @jobs.each do |job| %>
                <tr>
                  <td>

                        <%= image_tag job.profile_image_url, :class =>"img-circle", :width =>"100" %> 

                  </td>
                  <td>
                  
                    <% if job.status_code == 'Lined Up' %>
                    <span class="label label-warning pull-right"><%= job.status_code %> since <%= time_ago_in_words(job.created_at) %></span>
                    
                    <% else %>
                      <span class="label label-success pull-right"><%= job.status_code %> <%= time_ago_in_words(job.updated_at) %> ago</span>
                    <% end %>
                    
                    <strong><i class="icon-twitter"></i>  <%= link_to "@#{job.owner}", "http://www.twitter.com/#{job.owner}" %></strong><br/> <%=raw Rinku.auto_link(job.content, mode=:all) %>
                  </td>
               
            
                </tr>
              <% end %>
            </tbody>
          </table>
          <% end %>

          <h3>Videos</h3>

          

            <iframe width="100%" height="400" src="http://www.youtube.com/embed/lPcGAFuTVxg" frameborder="0" allowfullscreen></iframe>
            <p class="lead">Demo Video.</p>
            <p class="lead">
              <i class="icon-facetime-video icon-large"></i> This is what you should see during hours of operation.
            <iframe width="100%" height="400" src="http://www.youtube.com/embed/3T5DqVbl8Cg" frameborder="0" allowfullscreen></iframe>


       

        </div><!-- /.span4 -->
       
          <div class="span5">

            
            <h3><%= Job.count %> tweets printed so far</h3>
            <p>Read about it in the media:</p>
            <img src="https://pbs.twimg.com/media/BU209v7CMAAOzpt.jpg:large" width="100%" alt="Toronto Star, Kim Nursall">
            <hr/>
            
            <ul>
              <li><a href="http://www.thestar.com/news/gta/2013/09/21/toronto_mini_maker_faire_featuring_robots_and_3d_printing_a_family_affair.html" target="_blank">Toronto Star, with video</a></li>
              <li><a href="http://hackaday.com/2013/09/27/mechanical-typewriter-types-your-tweets/" target="_blank">Hack a day</a></li>
              <li><a href="http://www.betakit.com/shaping-tomorrows-makers-at-torontos-mini-maker-faire/" target="_blank">betakit</a></li>

            </ul>
            <a href="http://makerfairetoronto.com/" target="_blank"><img src='http://makerfairetoronto.files.wordpress.com/2013/06/toronto_mmf_logos_wordpress.png'></a>

            <hr/>


          <% if @settings.maintanance == true %>
          <div class="alert alert-block">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h4><i class="icon-ambulance icon-large"></i> Printing Services Temporarily Offline!</h4>
            <p><%= @settings.status %></p>
            
          </div>

          <% else %>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h4><i class="icon-bullhorn icon-large"></i> Printing Services Online!</h4>
            <p>Feel free to tweet now and watch it happen!</p>
          </div>

                            <p class="lead">
                    Getting your <i class="icon-twitter icon-large"></i> tweets printed is easy:</p><p class="lead"><strong>1.</strong> 

                  <a href="https://twitter.com/intent/tweet?screen_name=<%= Setting.last.twitter_user %>" class="twitter-mention-button" data-related="<%= Setting.last.twitter_user %>">Tweet to <%= Setting.last.twitter_user %></a>
                  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>



                    <p  class="lead"><strong>2.</strong> Hit <%= link_to refresh_jobs_path, :class => 'btn btn-success' do %>
              <i class="icon-print"></i> Print New Tweets 
          <% end %></p><p  class="lead"><strong>3.</strong> Watch it being printed on the <i class="icon-facetime-video icon-large"></i> live stream.</p>



                  </p>

          <% end %>




                    <p>Feel free to checkout <%= link_to "some videos of me typing", "http://www.youtube.com/watch?v=3T5DqVbl8Cg&feature=share&list=PL0BF6SJ3yFfSUuW_tw3MK73mTsZYbt21W" %> and the <%= link_to "blog posts about me", "http://michael.schwanzer.info/blog/?s=typewriter" %>.</p>
               <hr/>

               <!-- Place this tag where you want the +1 button to render. -->
               <a href="https://twitter.com/mschwanzer" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @mschwanzer</a>
               <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

               <a href="https://twitter.com/share" class="twitter-share-button" data-via="lepetiteprinter" data-size="large" data-related="mschwanzer" data-hashtags="printme">Tweet</a>
               <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>


               <div class="g-plusone" data-annotation="inline" data-width="300"></div>

               <!-- Place this tag after the last +1 button tag. -->
               <script type="text/javascript">
                 (function() {
                   var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                   po.src = 'https://apis.google.com/js/plusone.js';
                   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
                 })();
               </script>
               
            <div class="fb-like" data-href="http://lepetiteprintshop.com" data-send="true" data-width="450" data-show-faces="true"></div>
          
          <hr/>

          <h4><i class="icon-print icon-large"></i> Printing Services Provided</h4>
          <ul class="icons">
            <li><i class="icon-ok"></i> Input via Twitter, Email (if you need more than 140 characters)</li>
            <li><i class="icon-ok"></i> Black / Red Ribbon Colour</li>
            <li><i class="icon-ok"></i> Simple ASCII Images</li>
            <li><i class="icon-ok"></i> Business / Personal Letters, Custom Greeting Cards</li>
            <li><i class="icon-ok"></i> Rent Printer for your Event or Promotion. Contact Michael.</li>
          </ul>

          <hr/>

          <div class="media">
            <h4>Who is running this print shop?</h4>
            <a class="pull-left" href="#">
              <img src="https://twimg0-a.akamaihd.net/profile_images/1436288805/Screen_shot_2011-07-11_at_12.29.32_AM.png" class="img-circle media-object" width="100">
            </a>
            <div class="media-body">
          <p>Michael Schwanzer (<a href="http://www.twitter.com/mschwanzer">@mschwanzer</a>) is a strategic thinker who likes to apply his engineering, management and web skills to optimize processes and create new business opportunities.</p>
          <p>
            <%= link_to 'http://www.twitter.com/mschwanzer' do %>
                <i class="icon-twitter-sign icon-2x"></i>
            <% end %>
            <%= link_to 'http://www.linkedin.com/in/mschwanzer' do %>
                <i class="icon-linkedin-sign icon-2x"></i>
            <% end %> 

            <%= link_to 'http://www.facebook.com/mschwanzer' do %>
                <i class="icon-facebook-sign icon-2x"></i>
            <% end %> 

            <%= link_to 'http://www.github.com/mschwanzer' do %>
                <i class="icon-github-sign icon-2x"></i>
            <% end %> 

            <%= link_to 'https://plus.google.com/116247842016091212213' do %>
                <i class="icon-google-plus-sign icon-2x"></i>
            <% end %> 
            <%= link_to 'http://michael.schwanzer.info/blog' do %>
                <i class="icon-sign-blank icon-2x"></i> 
            <% end %>
          </p>
            </div>
          </div>

<hr class="featurette-divider">
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'lepetiteprintshop'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>



        </div><!-- /.span4 -->
      </div><!-- /.row -->

app/views/pages/pre_mf_hello.html.erb
   <div class="row">
        <div class="span7">

          <% if @settings.camera == true %>
          <p class="lead">
            <i class="icon-facetime-video icon-large"></i> Live Stream of Printing Process
            <img src="<%= @settings.camera_link %>video" alt="Typewriter Video feed"/><p>If no video appears above, you are using an unsupported browser. Tested browsers: <a href="http://www.firefox.com">Mozilla Firefox</a>, <a href="http://www.google.com/chrome">Google Chrome</a></p>
          <% else %>
            <iframe width="100%" height="400" src="http://www.youtube.com/embed/lPcGAFuTVxg" frameborder="0" allowfullscreen></iframe>
            <p class="lead">Demo Video. Live Stream only avaiable during hours of operation.</p>
            <p class="lead">
              <i class="icon-facetime-video icon-large"></i> This is what you should see during hours of operation.
            <iframe width="100%" height="400" src="http://www.youtube.com/embed/3T5DqVbl8Cg" frameborder="0" allowfullscreen></iframe>


          <% end %>

    
          <hr class="featurette-divider">

          <h3>Recent and Upcoming Jobs, so far <%= Job.count %> tweets printed</h3>

          <table class="table table-striped">
            <tbody>
              <% @jobs.each do |job| %>
                <tr>
                  <td>

                        <%= image_tag job.profile_image_url, :class =>"img-circle", :width =>"100" %> 

                  </td>
                  <td>
                  
                    <% if job.status_code == 'Lined Up' %>
                    <span class="label label-warning pull-right"><%= job.status_code %> since <%= time_ago_in_words(job.created_at) %></span>
                    
                    <% else %>
                      <span class="label label-success pull-right"><%= job.status_code %> <%= time_ago_in_words(job.updated_at) %> ago</span>
                    <% end %>
                    
                    <strong><i class="icon-twitter"></i>  <%= link_to "@#{job.owner}", "http://www.twitter.com/#{job.owner}" %></strong><br/> <%=raw Rinku.auto_link(job.content, mode=:all) %>
                  </td>
               
            
                </tr>
              <% end %>
            </tbody>
          </table>





        </div><!-- /.span4 -->
       
          <div class="span5">
            <h2>Visit the Typewriter this weekend!</h2>
            <a href="http://makerfairetoronto.com/" target="_blank"><img src='http://makerfairetoronto.files.wordpress.com/2013/06/toronto_mmf_logos_wordpress.png'></a>

          <% if @settings.maintanance == true %>
          <div class="alert alert-block">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h4><i class="icon-ambulance icon-large"></i> Printing Services Temporarily Offline!</h4>
            <p><%= @settings.status %></p>
            
          </div>

          <% else %>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h4><i class="icon-bullhorn icon-large"></i> Printing Services Online!</h4>
            <p>Feel free to tweet now and watch it happen!</p>
          </div>

          <% end %>

                  <p class="lead">
                    Getting your <i class="icon-twitter icon-large"></i> tweets printed is easy:</p><p class="lead"><strong>1.</strong> 
                    <a href="https://twitter.com/intent/tweet?button_hashtag=<%= Setting.last.hashtag %>&text=%40lepetiteprinter%20this%20cool%20typewriter%20will%20print%20this%20tweet%3A" class="twitter-hashtag-button" data-size="large" data-related="mschwanzer" data-url="http://www.lepetiteprintshop.com">Tweet #<%= Setting.last.hashtag %></a>
                    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                

                    <p  class="lead"><strong>2.</strong> Hit <%= link_to refresh_jobs_path, :class => 'btn btn-success' do %>
              <i class="icon-print"></i> Print New Tweets 
          <% end %></p><p  class="lead"><strong>3.</strong> Watch it being printed on the <i class="icon-facetime-video icon-large"></i> live stream. </p>



                  </p>


                    <p>Feel free to checkout <%= link_to "some videos of me typing", "http://www.youtube.com/watch?v=3T5DqVbl8Cg&feature=share&list=PL0BF6SJ3yFfSUuW_tw3MK73mTsZYbt21W" %> and the <%= link_to "blog posts about me", "http://michael.schwanzer.info/blog/?s=typewriter" %>.</p>
               <hr/>

               <!-- Place this tag where you want the +1 button to render. -->
               <a href="https://twitter.com/lepetiteprinter" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @lepetiteprinter</a>
               <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

               <a href="https://twitter.com/share" class="twitter-share-button" data-via="lepetiteprinter" data-size="large" data-related="mschwanzer" data-hashtags="printme">Tweet</a>
               <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>


               <div class="g-plusone" data-annotation="inline" data-width="300"></div>

               <!-- Place this tag after the last +1 button tag. -->
               <script type="text/javascript">
                 (function() {
                   var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                   po.src = 'https://apis.google.com/js/plusone.js';
                   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
                 })();
               </script>
               
            <div class="fb-like" data-href="http://lepetiteprintshop.com" data-send="true" data-width="450" data-show-faces="true"></div>
          
          <hr/>

          <h4><i class="icon-print icon-large"></i> Printing Services Provided</h4>
          <ul class="icons">
            <li><i class="icon-ok"></i> Input via Twitter, Email (if you need more than 140 characters)</li>
            <li><i class="icon-ok"></i> Black / Red Ribbon Colour</li>
            <li><i class="icon-ok"></i> Simple ASCII Images</li>
            <li><i class="icon-ok"></i> Business / Personal Letters, Custom Greeting Cards</li>
            <li><i class="icon-ok"></i> Rent Printer for your Event or Promotion. Contact Michael.</li>
          </ul>

          <hr/>

          <div class="media">
            <h4>Who is running this print shop?</h4>
            <a class="pull-left" href="#">
              <img src="https://twimg0-a.akamaihd.net/profile_images/1436288805/Screen_shot_2011-07-11_at_12.29.32_AM.png" class="img-circle media-object" width="100">
            </a>
            <div class="media-body">
          <p>Michael Schwanzer (<a href="http://www.twitter.com/mschwanzer">@mschwanzer</a>) is a strategic thinker who likes to apply his engineering, management and web skills to optimize processes and create new business opportunities.</p>
          <p>
            <%= link_to 'http://www.twitter.com/mschwanzer' do %>
                <i class="icon-twitter-sign icon-2x"></i>
            <% end %>
            <%= link_to 'http://www.linkedin.com/in/mschwanzer' do %>
                <i class="icon-linkedin-sign icon-2x"></i>
            <% end %> 

            <%= link_to 'http://www.facebook.com/mschwanzer' do %>
                <i class="icon-facebook-sign icon-2x"></i>
            <% end %> 

            <%= link_to 'http://www.github.com/mschwanzer' do %>
                <i class="icon-github-sign icon-2x"></i>
            <% end %> 

            <%= link_to 'https://plus.google.com/116247842016091212213' do %>
                <i class="icon-google-plus-sign icon-2x"></i>
            <% end %> 
            <%= link_to 'http://michael.schwanzer.info/blog' do %>
                <i class="icon-sign-blank icon-2x"></i> 
            <% end %>
          </p>
            </div>
          </div>

<hr class="featurette-divider">
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'lepetiteprintshop'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>



        </div><!-- /.span4 -->
      </div><!-- /.row -->